use_frameworks!

platform :ios, '10.0'

target 'UITextfieldWithSlideDownNote_Example' do
  pod 'UITextfieldWithSlideDownNote', :path => '../'

  target 'UITextfieldWithSlideDownNote_Tests' do
    inherit! :search_paths

    
  end
end
